Implemented core
BlocSoc-iitr/Athena pull request #16
Opened 2024-09-15 16:35 UTC by DarkLord017

2024-09-15 19:34 UTC, Sh0g0-1758 requested changes
Code Quality in general is not so good. You should go through the code once more.

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +	if groupedAbi["type_def"] == nil {
I don't think this is required.

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +	ClassHash             b256
I think we can simply go with []byte

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +type b256 [32]byte
This might not be required. simple []byte should do the job.

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +		defineTypes, errDtypes := ParseEnumsAndStructs(sortedDefs)
Can these not be combined into one statement ?

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +		log.Println("No interfaces found in ABI")
Again not really required.

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +		log.Println("No functions found in ABI")
ditto

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +	if groupedAbi["event"] == nil {
ditto.

2024-09-15 19:34 UTC, Sh0g0-1758 commented on athena_abi/core.go
> +	if len(parsedAbiEvents) == 0 {
ditto.

2024-09-16 09:45 UTC, DarkLord017 commented
Sir i tried to improve the code quality what can i improve more

2024-09-22 15:08 UTC, Sh0g0-1758 approved these changes
LGTM

2024-09-22 15:09 UTC, merged