Implemented event_decoders_test.go
BlocSoc-iitr/Athena pull request #20
Opened 2024-09-15 20:42 UTC by x-senpai-x

On line 41 I used a different value than what was used in python test suite due to discrepancy between the expected values in the Go and Python implementations for U256 .

2024-09-22 15:06 UTC, Sh0g0-1758 requested changes
In general, should be good to merge with a couple of nits.

2024-09-22 15:06 UTC, Sh0g0-1758 commented on athena_abi/event_decoders_test.go
> +func mustParseBigInt(s string, base int) *big.Int {
Move these helper functions to uitls.go

2024-09-22 15:06 UTC, Sh0g0-1758 commented on athena_abi/event_decoders_test.go
> +            abiEvent: NewAbiEvent(
How did you get this ? In the original code, I saw that they have loaded an abi for the testing purpose.

2024-09-22 15:06 UTC, Sh0g0-1758 commented on athena_abi/event_decoders_test.go
> +            abiEvent: NewAbiEvent(
Okay, Lets wait for core.go to be implemented. Then you can use from_json function from it.

2024-09-22 19:06 UTC, closed without merging

2024-09-23 05:13 UTC, x-senpai-x commented on athena_abi/event_decoders_test.go
> +            abiEvent: NewAbiEvent(
Do I need to incorporate starknetabifromjson?